<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NTS5CG7321YLY" ignored="0" name="Default test" tests="4" failures="1" timestamp="01 Oca 2019 21:03:14 GMT" time="182.014" errors="0">
  <testcase name="feature" time="44.583" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="38.769" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.Exception: Sth went wrong! Upps! taking a screenshoot!">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.Exception: Sth went wrong! Upps! taking a screenshoot!
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: Sth went wrong! Upps! taking a screenshoot!
at utility.HookA.verifyA(HookA.java:212)
at stepdefinitions.mystepdefinitions_A.usera_can_see_something_on_something_location(mystepdefinitions_A.java:254)
at âœ½.And UserA can see "close" on "contact.details.right.panel.close.button.text.area***************" location(src/test/resources/features/Contacts_TCs_2.feature:12)
]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="24.774" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="73.346" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Default test -->
